In [89]:
import pandas as pd
import sqlite3 as sqdb
import matplotlib.pyplot as plt

divider = ('-' * 50)
# getting started
# A Series is a one-dimensional array-like object containing an array of data (of anyNumPy data type)
# and an associated array of data labels, called its index.
obj = pd.Series([4, 7, -5, 3])
print(obj)
print('object.values:', obj.values)
obj_ = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'e'])
print(obj_)

0    4
1    7
2   -5
3    3
dtype: int64
object.values: [ 4  7 -5  3]
a    4
b    7
c   -5
e    3
dtype: int64

### Esential Functionality
#### Reindexing

In [64]:
obj = pd.Series([4.5, 7.2, 5, 3], index=['a', 'b', 'c', 'd'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)
print(obj2)
print()
obj3 = pd.Series(['Blue', 'Purple', 'Yellow'], index=[0, 2, 4])
print(obj3)
obj3.reindex(range(6), method='ffill')

a    4.5
b    7.2
c    5.0
d    3.0
dtype: float64
a    4.5
b    7.2
c    5.0
d    3.0
e    NaN
dtype: float64
a    4.5
b    7.2
c    5.0
d    3.0
e    0.0
dtype: float64

0      Blue
2    Purple
4    Yellow
dtype: object

0      Blue
1      Blue
2    Purple
3    Purple
4    Yellow
5    Yellow
dtype: object

## Starting with pandas
- query : `df = pd.read_sql_query("SELECT * FROM table_name", conn) `
- csv file: `df = pd.read_csv(filename.csv)`
- csv file: `df = pd.read_csv(filename.csv, encoding='utf-8' )`
- tab separated file : `df = pd.read_csv(filename.txt, delimiter='\t')`
- excel file: `df = pd.read_excel(filename.xlsx)`

In [115]:
# reading data from sqlite database
db_name = '/home/dabve/programming/python/project/gestion_stocks/etatsStocksPDR.sqlite'
conn = sqdb.connect(db_name)
query = 'SELECT designation, code, reference, qte, prixU, valeur FROM magasin_pdr'
df = pd.read_sql_query(query, conn)
# OR
# curs.execute(query)
# desc = [desc[0] for desc in curs.description]
# rows = curs.fetchall()
# df = pd.DataFrame.from_records(data=rows, columns=desc)

print(df.head(10))                      # head or tail like in bash, take number of line as argument
print(divider)
print('Number of rows: {}'.format(len(df)))
print('Columns: {}'.format(df.columns))
print('Columns as a list: {}'.format(list(df.columns)))
print(divider)
print()
print('Get a specific columns: \n{}'.format(df.code))     # or df['code']
print()
print('Like limit in SQL: \n{}'.format(df['code'][:5]))
print()
print('Multiple Columns: \n{}'.format(df[{'designation', 'code', 'qte', 'prixU'}][:6]))
print()

             designation     code reference  qte    prixU    valeur
0                    AXE  ARO-002     93084   12  3000.00  36000.00
1                    AXE  ARO-003     93088   10  3000.00  30000.00
2               CIRCLIPS  ARO-004     77802   20   200.00   4000.00
3  MEMBRANE (DIAPHRAGME)  ARO-005   93465-G    1  5932.53   5932.53
4                GRAISSE  ARO-006   93706-1    1   548.19    548.19
5          JOINT TORIQUE  ARO-007     93075   13   179.09   2328.17
6                  JOINT  ARO-008     93107    7  2000.00  14000.00
7                  JOINT  ARO-009     93116   23   997.59  22944.57
8                  JOINT  ARO-010     93265    6  1000.00   6000.00
9                  JOINT  ARO-011   93339.1   12   350.00   4200.00
--------------------------------------------------
Number of rows: 3048
Columns: Index(['designation', 'code', 'reference', 'qte', 'prixU', 'valeur'], dtype='object')
Columns as a list: ['designation', 'code', 'reference', 'qte', 'prixU', 'valeur']
--------------------------------------------------

Get a specific columns:
0         ARO-002
1         ARO-003
2         ARO-004
3         ARO-005
4         ARO-006
          ...
3043      ASI-140
3044    CHAUD-041
3045    M924-0162
3046    ATLAS-023
3047    ATLAS-024
Name: code, Length: 3048, dtype: object

Like limit in SQL:
0    ARO-002
1    ARO-003
2    ARO-004
3    ARO-005
4    ARO-006
Name: code, dtype: object

Multiple Columns:
     prixU            designation  qte     code
0  3000.00                    AXE   12  ARO-002
1  3000.00                    AXE   10  ARO-003
2   200.00               CIRCLIPS   20  ARO-004
3  5932.53  MEMBRANE (DIAPHRAGME)    1  ARO-005
4   548.19                GRAISSE    1  ARO-006
5   179.09          JOINT TORIQUE   13  ARO-007

### Making changes

In [ ]:
df['valeur'] = df['qte'] * df['prixU']
# work with indexes, the first part means all rows, and the second mean the 5, and 6 columns
# axis = 1: horizontaly, and 0 for verticaly
df['valeur'] = df.iloc[:, 5:7].sum(axis=1)

del df['valeur']                            # delete column 'valeur'
df = df.drop(columns=['valeur'])            # drop column
df = df.drop('valeur', axis=1)              # drop column

### Working with rows

In [39]:
print(df.loc[0:3])          # loc: label based index
print()
print(df.iloc[1])           # positional argument
print()
print(df.iloc[1:5])
print()
print(df.iloc[2,1])         # get a specific row and columns, 2, 1 == second row, first one

# iterate through rows
print('\nIterate through all rows: \n')
for index, row in df.iterrows():
    # this will print a details for all records
    print('index: {}\n{}'.format(index, row))
    print(divider)
    if index == 5: break

# search where qte == 0
print('\nQuantité = 0')
print(df.loc[df['qte'] == 0][:10])
# Statistics
print(df.describe())

             designation     code reference  qte    prixU    valeur
0                    AXE  ARO-002     93084   12  3000.00  36000.00
1                    AXE  ARO-003     93088   10  3000.00  30000.00
2               CIRCLIPS  ARO-004     77802   20   200.00   4000.00
3  MEMBRANE (DIAPHRAGME)  ARO-005   93465-G    1  5932.53   5932.53

designation        AXE
code           ARO-003
reference        93088
qte                 10
prixU             3000
valeur           30000
Name: 1, dtype: object

             designation     code reference  qte    prixU    valeur
1                    AXE  ARO-003     93088   10  3000.00  30000.00
2               CIRCLIPS  ARO-004     77802   20   200.00   4000.00
3  MEMBRANE (DIAPHRAGME)  ARO-005   93465-G    1  5932.53   5932.53
4                GRAISSE  ARO-006   93706-1    1   548.19    548.19

ARO-004

Iterate through all rows:

index: 0
designation        AXE
code           ARO-002
reference        93084
qte                 12
prixU             3000
valeur           36000
Name: 0, dtype: object
--------------------------------------------------
index: 1
designation        AXE
code           ARO-003
reference        93088
qte                 10
prixU             3000
valeur           30000
Name: 1, dtype: object
--------------------------------------------------
index: 2
designation    CIRCLIPS
code            ARO-004
reference         77802
qte                  20
prixU               200
valeur             4000
Name: 2, dtype: object
--------------------------------------------------
index: 3
designation    MEMBRANE (DIAPHRAGME)
code                         ARO-005
reference                    93465-G
qte                                1
prixU                        5932.53
valeur                       5932.53
Name: 3, dtype: object
--------------------------------------------------
index: 4
designation    GRAISSE
code           ARO-006
reference      93706-1
qte                  1
prixU           548.19
valeur          548.19
Name: 4, dtype: object
--------------------------------------------------
index: 5
designation    JOINT TORIQUE
code                 ARO-007
reference              93075
qte                       13
prixU                 179.09
valeur               2328.17
Name: 5, dtype: object
--------------------------------------------------

Quantité = 0
                        designation        code                     reference  \
133                           BRIDE     ASI-132                         DN 95
150      BARRE DE PINCE (1575  EEG)  AUTOP-0045      0480 5672 00 0480 0000YF
208                    DOUILLE PETP  AUTOP-0131        Øext= 39.25 Øint= 35.5
272                  AXE POUR GALET  AUTOP-0207                          Null
406               VÉRIN PNEUMATIQUE  AUTOP-0424  RA/8050/M/250 (1140 2050 12)
432               FIL SOUPLE UL 600  AUTOP-0465                   5868 900 16
449                          RELAIS  AUTOP-0493                       788-516
455                          RELAIS  AUTOP-0501                    ABR 2E112B
456  FIN DE COURSE POUSSOIR A GALET  AUTOP-0502                    2318510400
491                   FIN DE COURSE  AUTOP-0561                  2318 5001 00

     qte     prixU  valeur
133    0   2500.00     0.0
150    0  86812.50     0.0
208    0    250.00     0.0
272    0   2200.00     0.0
406    0   5400.00     0.0
432    0    100.00     0.0
449    0    900.00     0.0
455    0   1000.00     0.0
456    0   1413.13     0.0
491    0   2600.00     0.0
               qte         prixU        valeur
count  3048.000000  3.048000e+03  3.048000e+03
mean      7.579724  2.001984e+04  5.127150e+04
std      30.664421  8.705097e+04  1.832969e+05
min       0.000000  0.000000e+00  0.000000e+00
25%       1.000000  8.000000e+02  2.300000e+03
50%       2.000000  3.000000e+03  8.536500e+03
75%       6.000000  1.118839e+04  3.202770e+04
max     976.000000  2.841091e+06  5.055030e+06

### Filtering Data

In [112]:
print(df.loc[df['designation'] == 'Fusible'])
print()
print(df.loc[(df['designation'] == 'Fusible') & (df['code'] == 'GOP-009')])
print()
print(df.loc[(df['designation'] == 'Fusible') & (df['qte'] > 10)])
print(divider)
axe_desig = df.loc[(df['designation'] == 'AXE') & (df['qte'] >=3)]
print('[+] With original index\n', axe_desig)
axe_desig.reset_index(drop=True, inplace=True)
print(divider)
print('[+] Reseting index\n', axe_desig)

     designation     code  reference  qte   prixU   valeur
2967     Fusible  GOP-009  100A 500V   11  6300.0  69300.0
2990     Fusible  EI-0344   50A 690V    9    88.5    796.5

     designation     code  reference  qte   prixU   valeur
2967     Fusible  GOP-009  100A 500V   11  6300.0  69300.0

     designation     code  reference  qte   prixU   valeur
2967     Fusible  GOP-009  100A 500V   11  6300.0  69300.0
--------------------------------------------------
[+] With original index
      designation        code       reference  qte     prixU     valeur
0            AXE     ARO-002           93084   12   3000.00   36000.00
1            AXE     ARO-003           93088   10   3000.00   30000.00
164          AXE  AUTOP-0080    0636 2175 00    3   1100.00    3300.00
346          AXE  AUTOP-0335       693102900    3   1800.00    5400.00
376          AXE  AUTOP-0383    1010 5300 09    5   2093.13   10465.65
536          AXE  AUTOP-0634    1010 5250 15    4   1529.38    6117.52
861          AXE    BHS-0304           93088    7  25000.00  175000.00
1632         AXE   M618-0223       0337.4595    4  45897.59  183590.36
1658         AXE   M618-0276       0398.4813    6   5868.42   35210.52
2039         AXE     MOS-001  2401-015100-05    6   2300.00   13800.00
--------------------------------------------------
[+] Reseting index
   designation        code       reference  qte     prixU     valeur
0         AXE     ARO-002           93084   12   3000.00   36000.00
1         AXE     ARO-003           93088   10   3000.00   30000.00
2         AXE  AUTOP-0080    0636 2175 00    3   1100.00    3300.00
3         AXE  AUTOP-0335       693102900    3   1800.00    5400.00
4         AXE  AUTOP-0383    1010 5300 09    5   2093.13   10465.65
5         AXE  AUTOP-0634    1010 5250 15    4   1529.38    6117.52
6         AXE    BHS-0304           93088    7  25000.00  175000.00
7         AXE   M618-0223       0337.4595    4  45897.59  183590.36
8         AXE   M618-0276       0398.4813    6   5868.42   35210.52
9         AXE     MOS-001  2401-015100-05    6   2300.00   13800.00

### Sorting and describing data

In [91]:
import re
new_df = df[{'designation', 'code', 'qte', 'prixU'}]
print(new_df.sort_values(['code']))
print(divider)
code = new_df.loc[new_df['code'].str.contains('^-', flags=re.I, regex=True)]
# bhs_article = df.loc[df['code'].str.contains('BHS')]
print(code.sort_values(['code', 'qte']).head(15))
print(divider)
print(code.sort_values(['code'], ascending=False).head(15))

          prixU                        designation  qte     code
3042  290000.00            Moteur Electrique Lenze    1
2844   60915.85              Arbre  pour imprimeur    2        -
2845   48117.74               Arbre pour imprimeur    2        -
2846    9543.82  pignon de chaine  pour séparateur    2        -
2847   25862.88             profile  pour empileur    4        -
...         ...                                ...  ...      ...
2835    1535.00                              JOINT   11  WIL-005
2836    1031.74          Joint De plaque silenciex    5  WIL-006
2837     650.41                 BOULE NEOPRENE 2''    2  WIL-010
2838   12000.00                         ARBRE INOX    3  WIL-019
2839    4500.00                              ARBRE   12  WIL-020

[3048 rows x 4 columns]
--------------------------------------------------
           prixU                           designation  qte code
2840  1078804.34        Arbre de détour   pour margeur    1    -
2841     5006.60               courroie   pour margeur    1    -
2843    15872.81                 poulie pour imprimeur    1    -
2862   634898.90                          servomoteur     1    -
2874    53136.16                           Upper beam     1    -
2878    18154.77                    Alu profile upper     1    -
2883    28349.57                             Cam disc     1    -
2898   129833.19          charger de batterie 332-8816    1    -
2899   107000.00        Bande transportouse PVC striee    1    -
2904   648135.87                   MODULE PROGRAMABLE     1    -
2842    12600.84               poulie  pour imprimeur     2    -
2844    60915.85                 Arbre  pour imprimeur    2    -
2845    48117.74                  Arbre pour imprimeur    2    -
2846     9543.82     pignon de chaine  pour séparateur    2    -
2853    43181.89  courroie de transport pour découpeur    2    -
--------------------------------------------------
           prixU                         designation  qte code
2840  1078804.34      Arbre de détour   pour margeur    1    -
2891    22862.56                        Cuting plate   20    -
2863    53180.11     revetement des cylindes découpe   18    -
2864   757742.01                     Servo variateur    2    -
2872    29329.01      Complete central locking unit     4    -
2874    53136.16                         Upper beam     1    -
2875     1623.38                                Bolt    4    -
2878    18154.77                  Alu profile upper     1    -
2879     2299.78  Spring for upper strinning frame      4    -
2883    28349.57                           Cam disc     1    -
2893    28936.70                      Gipper profite   10    -
2841     5006.60             courroie   pour margeur    1    -
2895     2678.57                     Gripper spring    40    -
2897     1082.25     Spring for lower stripping tool    2    -
2898   129833.19        charger de batterie 332-8816    1    -

In [101]:
bhs_article = new_df.loc[df['code'].str.contains('BHS')]
print(bhs_article)
print(divider)
# ~ == not contain
# bhs_article = df.loc[ ~ df['code'].str.contains('BHS')]
search = df.loc[(df['code'].str.contains('BHS')) & (df['qte'] <= 3)]
print(search[{'designation', 'code', 'qte', 'prixU'}].sort_values(['qte']))
print(divider)
bhs_autop = new_df.loc[df['code'].str.contains('bhs|autop', flags=re.I, regex=True)]
print(bhs_autop.head(15))
print()
print(bhs_autop.tail(15))
print(divider)
moteur = new_df.loc[df['designation'].str.contains('^moteur', flags=re.I, regex=True)]
print(moteur[{'designation', 'code'}])

          prixU          designation  qte        code
701     3164.44     ELEMENT FILTRANT    3    BHS-0003
702     3500.00        POTENTIOMETRE    2    BHS-0005
703     9000.00    CAPTEUR CAPACITIF    3    BHS-0006
704    12000.00  ACCESSOIRE COMPTEUR    1    BHS-0009
705     5897.44    MOTEUR ELECTRIQUE    1    BHS-0010
...         ...                  ...  ...         ...
2982  624054.47            Variateur    0    BHS-0260
3001   54000.00       Vis De Blocage   45    BHS-0792
3002    4700.00        Pignon Double    3  BHS-0734/C
3003   12000.00            Detecteur    1    BHS-0106
3013  374330.00         Servo Moteur    1    BHS-0953

[494 rows x 4 columns]
--------------------------------------------------
          prixU                   designation  qte      code
1058     250.00                  JOIN TORIQUE    0  BHS-0713
1150      71.40            VIS À TETE CONIQUE    0  BHS-0896
1115    1500.00           SOUPAPE ANTI-RETOUR    0  BHS-0834
1069  344090.91            CARTE ELECTRONIQUE    0  BHS-0739
1169  276705.00  MODULE DE RÉINJECTION RÉSEAU    0  BHS-0965
...         ...                           ...  ...       ...
802     1851.85                        MODULE    3  BHS-0188
796    22000.00      INTERRUPTEUR DE POSITION    3  BHS-0178
790     1000.00                       FUSIBLE    3  BHS-0165
1088   50012.35     NOPPLE MAMELON POUR BOITE    3  BHS-0765
701     3164.44              ELEMENT FILTRANT    3  BHS-0003

[328 rows x 4 columns]
--------------------------------------------------
        prixU                                designation  qte        code
136  46784.34                       ECHANGEUR DE CHALEUR    1  AUTOP-0005
137   3235.94                              RESSORT À GAZ    3  AUTOP-0006
138   1172.64  TÊTE BOUTON TOURNANT LUMINEUX 3 POSITIONS    9  AUTOP-0015
139   1800.00                              FIN DE COURSE    1  AUTOP-0018
140    626.09                            AXE POUR CHAINE   63  AUTOP-0021
141  25300.00                  BOBINE DU FREIN DU MOTEUR    4  AUTOP-0023
142    153.75                             JOINT  TORIQUE    9  AUTOP-0026
143  48850.00              GLISSIÈRE (ROULEMENTLINÉAIRE)    2  AUTOP-0033
144     92.00                          RESSORT DE GRIFFE   19  AUTOP-0035
145   1500.00                    PIGNON (ROUE DE CHAINE)    2  AUTOP-0036
146   5975.00                         DÉTECTEUR INDUCTIF    2  AUTOP-0037
147   1200.00                   DISTRIBUTEUR PNEUMATIQUE    1  AUTOP-0038
148  13200.00                         MODULE D'INTERFACE    1  AUTOP-0039
149   4200.00                                     PIGNON    2  AUTOP-0041
150  86812.50                 BARRE DE PINCE (1575  EEG)    0  AUTOP-0045

          prixU               designation  qte        code
2866  298125.88           SERVO VARIATEUR    2    BHS-0257
2935  116790.00          Automate (carte)    1    BHS-0021
2936    2000.00       Accessoire compteur    1    BHS-0008
2937    7157.89                     Racle    3    BHS-0489
2938    4800.00                  Membrane   10    BHS-0454
2971  130361.45                 Variateur    1  BHS-0257/U
2972  333428.98          Servo Régulateur    3    BHS-0249
2982  624054.47                 Variateur    0    BHS-0260
2983    1200.00  Distributeur Pneumatique    1  AUTOP-0314
3001   54000.00            Vis De Blocage   45    BHS-0792
3002    4700.00             Pignon Double    3  BHS-0734/C
3003   12000.00                 Detecteur    1    BHS-0106
3007   73375.00        Carte Electronique    1  AUTOP-0766
3008   30000.00        Carte Electronique    1  AUTOP-0765
3013  374330.00              Servo Moteur    1    BHS-0953
--------------------------------------------------
                            designation       code
705                   MOTEUR ELECTRIQUE   BHS-0010
812                     MOTEUR DE COLLE   BHS-0207
931                              MOTEUR   BHS-0459
932                              MOTEUR   BHS-0461
933                  MOTEUR PNEUMATIQUE   BHS-0463
1162              MOTEUR D'AIR COMPRIMÉ   BHS-0958
1222  MOTEUR ÉLECTRIQUE TYPE ST 5112-33  CHAUD-072
1400                  MOTEUR ELECTRIQUE    EI-0437
1688        MOTEUR ÉLECTRIQUE BAUMULLER  M618-0361
1689                   MOTEUR Reducteur  M618-0363
1690            MOTEUR ÉLECTRIQUE LENZE  M618-0365
1847                   MOTEUR REDUCTEUR  M924-0381
2154            MOTEUR 230/400V 0.25 KW    MOS-178
2162             MOTEUR COURANT CONTINU    MOS-188
2421                  MOTEUR HYDROLIQUE     PB-064
2903            Moteur acynchrone Frein          -
3042            Moteur Electrique Lenze

In [120]:
print('Somme des valeur BHS: {}'.format(df.loc[df['code'].str.contains('BHS')]['valeur'].sum()))
print('Somme Total des Articles: {}'.format(df['valeur'].sum()))

Somme des valeur BHS: 44939707.58
Somme Total des Articles: 156275543.9053

### Grouping

In [126]:
grouped = bhs_article.groupby(bhs_article['qte'])
print('Article par quantité')
print(grouped.size())
print(divider)

Article par quantité
qte
0       26
1      158
2       93
3       51
4       41
5       20
6       15
7        5
8        9
9       10
10       8
11       4
12       5
13       1
14       6
15       4
16       3
17       1
19       6
20       3
25       3
26       1
27       2
29       1
30       1
32       1
34       1
36       1
42       1
45       2
60       1
61       1
70       1
71       1
75       1
85       1
97       1
100      1
150      1
315      1
663      1
dtype: int64
--------------------------------------------------

### Save to file

In [ ]:
colnames = list(new_df.columns.values)
df_toSave = new_df[colnames[0:4]]                           # specify columns

df_toSave.to_csv('fileOut.csv')                             # write as csv file
df_toSave.to_csv('fileOut.csv', index=False)                # no index

df_toSave.to_excel('fileOut.xlsx', index=False)             # to excel
print('done creating your report')